#!/bin/bash
set -e

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

echo "[pre-commit] Running pre-commit checks..."

# --- Step 1: Sync mirrors if config/source/** was modified ---
if git diff --cached --name-only | grep -q "^config/source/"; then
  echo "[pre-commit] config/source/ modified, running sync:config..."
  node scripts/sync-config.mjs

  # Stage any mirror files updated by the sync
  # All-editor mirror (generated by sync-config.mjs)
  for dir in config/.claude/skills/ config/.cursor/rules/ config/.github-copilot/rules/ \
              config/.windsurf/rules/ config/.codebuddy/skills/ config/.augment/guidelines/ \
              config/.aider/rules/ config/.opensumi/rules/ config/.kiro/steering/ \
              config/.qoder/rules/ config/.trae/rules/; do
    if [ -d "$dir" ]; then
      git add "$dir" 2>/dev/null || true
    fi
  done

  # Claude-mirror (sync-claude-skills-mirror.mjs)
  for dir in .agent/rules/ .cline/rules/ .cursor/rules/ .github-copilot/rules/ \
              .windsurf/rules/ .codebuddy/skills/ .augment/guidelines/ \
              .opensumi/rules/ .kiro/steering/ .qoder/rules/ .trae/rules/; do
    if [ -d "$dir" ]; then
      git add "$dir" 2>/dev/null || true
    fi
  done

  if ! git diff --cached --quiet; then
    echo "[pre-commit] Mirror files updated and staged."
  fi
else
  echo "[pre-commit] Skipping sync:config (config/source/ not modified)."
fi

# --- Step 2: Build check (MUST pass) ---
echo "[pre-commit] Running npm run build..."
npm run build
if [ $? -ne 0 ]; then
  echo "[pre-commit] ERROR: npm run build failed. Fix errors before committing."
  exit 1
fi

echo "[pre-commit] All checks passed."
